### ISSUE TITLE
delegates.mgk

### ISSUE THREAD

**Issue by sander3** [wader/static-gm#102]
Hi there,

Thank you so much for creating the easiest way to include GraphicsMagick in a Docker image. I've converted/identified millions of images using your image!

From time-to-time I'm getting this error about a missing file. Researching the issue online I see that this file is normally stored in user space, but this being a static binary I'm not sure how to resolve the issue.

```
gm identify -format '%wx%hx%[exif:orientation]\n' '/app/storage/tmp/648fae746ec27b90e042f82941fa9fdea5445ae7da19d190398cf0619e24d958.jpg'

Unable to access configuration file (delegates.mgk) [No such file or directory].
```

**Comment by sander3** [comment]
I couldn't find a build flag either.

In terms of behavior I would expect the following result:
```
gm identify: No decode delegate for this image format (yarn.lock).
```

This is also quite interesting, it's looking for a `delegates.mgk` file in the current path:
```
/app # gm convert -list delegates
Path: delegates.mgk

Delegate             Command
-------------------------------------------------------------------------------
gm convert: Unable to access configuration file (delegates.mgk) [No such file or directory].
```

**Comment by wader** [comment]
Ok, looking at the code it seem to look in various places but in the a `.magick` directory, but i noticed there is `MAGICK_CONFIGURE_PATH` so this seems to work:
```sh
$ cat delegates.mgk
<?xml version="1.0"?>
<delegatemap>
</delegatemap>

$ docker run --rm -e MAGICK_CONFIGURE_PATH=$PWD -u $UID:$GROUPS -v "$PWD:$PWD" -w "$PWD" mwader/static-gm:1.3.38 identify b24046e8-015e-5b0e-b0f6-2418105ed0ee
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
/gm identify: No decode delegate for this image format (b24046e8-015e-5b0e-b0f6-2418105ed0ee).
/gm identify: Request did not return an image.
```

So maybe a possible solution is to ship an empty delegates.mgk with the docker image and set `MAGICK_CONFIGURE_PATH=/delegates.mgk` for the container and also document in README.md how to do if your copying the binary into some other image?

The only other option i can see is to somehow patch the source to make be not support delegates at all, feels a bit hacky and less maintainable?
